name: 'narval'

services:
  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    networks:
      - armory-local
    volumes:
      - ./.data/psql:/var/lib/postgresql/data

  redis:
    image: 'bitnami/redis:7.0'
    ports:
      - '6379:6379'
    expose:
      - '6379'
    networks:
      - armory-local
    environment:
      ALLOW_EMPTY_PASSWORD: 'true'
    logging:
      driver: none
    volumes:
      - ./.data/redis:/data

networks:
  armory-local:
