version: '3.8'
name: 'narval'
services:
  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  vault:
    build:
      context: .
      dockerfile: vault.dockerfile
    ports:
      - '3011:3011'
volumes:
  postgres_data:
    driver: local
