rules:
  style:
    # TODO: reactivate that rule

    rule-length:
      level: ignore
    # TODO: reactivate that rule
    line-length:
      level: ignore
    todo-comment:
      # don't error on TODO comments
      level: warning
    prefer-snake-case:
      # At Narval, we use camel case to comply with our naming conventions
      level: ignore
    external-reference:
      # TODO: set back to error and authorize external references only in entity/input querying packages
      level: ignore
    messy-incremental-rule:
      level: warning
  custom:
    # custom rule configuration
    prefer-camel-case:
      regex: '^[a-z]+([A-Z][a-z0-9]+)*$'
      level: error
      message: Names should use camelCase
  idiomatic:
    # TODO: reactivate without test file
    # figure out 'main' package vs 'criteria'
    directory-package-mismatch:
      level: warning

    no-defined-entrypoint:
      # TODO: make that thing pass
      level: warning
  testing:
    test-outside-test-package:
      level: ignore
