name: Packages CI

on:
  push:
    paths:
      - packages/**
      - .github/workflows/packages.yml
      - jest.config.ts
      - jest.preset.js
      - .eslintrc.json
      - .prettierrc
      - package.json
      - package-lock.json

jobs:
  build-and-test:
    name: Build and test

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.4.0'

      - name: Install dependencies
        run: |
          make install/ci

      - name: Set base and head SHAs for nx affected
        uses: nrwl/nx-set-shas@v3

      # Needed for nx affected to work when CI is running on a PR.
      - name: Track git main branch
        run: |
          git branch --track main origin/main

      - name: Code format
        run: |
          npx nx affected --target format:check lint:check

      - name: Test types
        run: |
          npx nx affected --target test:type

      - name: Test unit
        run: |
          npx nx affected --target test:unit

      - name: Test integration
        run: |
          npx nx affected --target test:integration

      - name: Test end-to-end
        run: |
          npx nx affected --target test:e2e

      - name: Send Slack notification on failure
        if: failure() && github.ref == 'refs/heads/main'
        uses: 8398a7/action-slack@v3
        with:
          username: GitHub
          author_name: '@narval/signature CI failed'
          status: ${{ job.status }}
          fields: message,commit,author
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
