name: '@app/policy-engine CI'

on:
  push:
    paths:
      - apps/policy-engine/**
      - .github/workflows/policy_engine_ci.yml
      - jest.config.ts
      - jest.preset.js
      - .eslintrc.json
      - .prettierrc
      - package.json
      - package-lock.json

jobs:
  build-and-test:
    name: Build and test

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.4.0'

      - name: Install dependencies
        run: |
          make install/ci

      - name: Code format
        shell: bash
        run: |
          make policy-engine/format/check
          make policy-engine/lint/check

      - name: Setup database and Prisma types
        shell: bash
        run: |
          make policy-engine/copy-default-env

      - name: Test types
        shell: bash
        run: |
          make policy-engine/test/type

      - name: Test unit
        shell: bash
        run: |
          make policy-engine/test/unit

      - name: Test integration
        shell: bash
        run: |
          make policy-engine/test/integration

      - name: Test E2E
        shell: bash
        run: |
          make policy-engine/test/e2e

      - name: Send Slack notification on failure
        if: failure() && github.ref == 'refs/heads/main'
        uses: 8398a7/action-slack@v3
        with:
          username: GitHub
          author_name: '@app/policy-engine CI failed'
          status: ${{ job.status }}
          fields: message,commit,author
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

  opa-rego:
    name: Open Agent Policy CI

    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup OPA
        uses: open-policy-agent/setup-opa@v2
        with:
          version: latest

      - name: Run OPA Tests
        run: make policy-engine/rego/test
